name: PyArrow & TF repro

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  bug-repro:
    runs-on: macos-14

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install tensorflow==2.20.0rc0 pyarrow==21.0.0
          python -c 'import tensorflow; import pyarrow'
